### ISSUE TITLE
Gem naming!

### ISSUE THREAD

**Issue by arbox** [genya0407/daru-plotly#1]
Hi @genya0407 ,

it would be probably better to follow the gem naming conventions: http://guides.rubygems.org/name-your-gem/

Since you have a submodule of `Daru` it's better to name the lib `daru-plotly`, not `daru_plotly`, which suggests the module `DaruPlotly`. 

Anyway thank you!

**Comment by genya0407** [comment]
Thanks @arbox, I'll work on it.

**Comment by genya0407** [comment]
Fixed: bd86e1bfb9700c92a6ac3e690dc9b73d1d0ab254
